### ISSUE TITLE
Python 2.7 performance with dict.keys()

### ISSUE THREAD

**Issue by ignaciordc** [egeulgen/Bioinformatics_Textbook_Track#1]
In BA6E.py there are a couple of lines that read
`    if key in seq1dict.keys():`
Instead of that the code should be:
`    if key in seq1dict:`

The reason for that is that when the dictionary seq1dict grows several tens of thousand keys, the performance is very, very poor, while the proposed code behaves perfectly. That happens in Python 2.7, not sure if that also affects Python 3.

This misbehavior can be confirmed with genomes with just 100.000 nuclueotids. A few seconds for a dict with 5000 keys turns into minutes with 50.000 keys.

**Comment by egeulgen** [comment]
Thanks for the heads up!
